# import the required libraries

In [1]:
import numpy as np
import pandas as pd

# Load Books dataset 

In [2]:
books = pd.read_csv("BX-Books.csv", 
            sep=';',
            encoding= 'latin-1',
            low_memory=False,
            on_bad_lines='skip')

In [3]:
type(books)

pandas.core.frame.DataFrame

In [4]:
books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford                2002     Oxford University Press   
1  Richard Bruce Wright                2001       HarperFlamingo Canada   
2          Carlo D'Este                1991             HarperPerennial   
3      Gina Bari Kolata                1999        Farrar Straus Giroux   
4       E. J. W. Barber                1999  W. W. Norton &amp; Company   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [5]:
books.shape

(271360, 8)

In [6]:
271379 - 271360

19

In [7]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [8]:
books.iloc[0]

ISBN                                                          0195153448
Book-Title                                           Classical Mythology
Book-Author                                           Mark P. O. Morford
Year-Of-Publication                                                 2002
Publisher                                        Oxford University Press
Image-URL-S            http://images.amazon.com/images/P/0195153448.0...
Image-URL-M            http://images.amazon.com/images/P/0195153448.0...
Image-URL-L            http://images.amazon.com/images/P/0195153448.0...
Name: 0, dtype: object

In [9]:
books.drop(['Image-URL-S','Image-URL-M'],axis=1,inplace=True)

In [10]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-L'],
      dtype='object')

In [11]:
# rename the columns of the data frame
books.rename(columns={'Book-Title':'title', 
                      'Book-Author':'author', 
                      'Year-Of-Publication':'year', 
                      'Publisher':'publisher',
                      'Image-URL-L':'image_url'
},inplace=True)

In [12]:
books.columns

Index(['ISBN', 'title', 'author', 'year', 'publisher', 'image_url'], dtype='object')

# Load Books ratings dataset 

In [13]:
ratings = pd.read_csv("BX-Book-Ratings.csv", 
            sep=';',
            encoding= 'latin-1',
            low_memory=False,
            on_bad_lines='skip')

In [14]:
ratings.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [15]:
ratings.shape

(1149780, 3)

In [16]:
ratings.rename(columns={"User-ID" :'user_id',
                        "Book-Rating":'rating'
},inplace=True)

In [17]:
ratings.columns

Index(['user_id', 'ISBN', 'rating'], dtype='object')

# Load the User dataset

In [18]:
users = pd.read_csv("BX-Users.csv", 
            sep=';',
            encoding= 'latin-1',
            low_memory=False,
            on_bad_lines='skip')

In [19]:
users.head()

User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [20]:
users.columns

Index(['User-ID', 'Location', 'Age'], dtype='object')

In [21]:
users.shape

(278858, 3)

In [22]:
# Lets remane some wierd columns name
users.rename(columns={"User-ID":'user_id',
                      'Location':'location',
                     "Age":'age'},inplace=True)

In [23]:
users.columns

Index(['user_id', 'location', 'age'], dtype='object')

# Shapes of the Datasets

In [24]:
books.shape, ratings.shape, users.shape

((271360, 6), (1149780, 3), (278858, 3))

# Users who has given more number of times ratings(read more books)

## Example

In [25]:
import pandas as pd

ratings1 = pd.DataFrame({
    'user_id': [1,1,1,2,2,3,3,3,3,3],
    'book_id': [10,11,12,10,13,11,12,14,15,16],
    'rating':  [5,4,3,5,4,2,3,4,5,3]
})

print(ratings1)

   user_id  book_id  rating
0        1       10       5
1        1       11       4
2        1       12       3
3        2       10       5
4        2       13       4
5        3       11       2
6        3       12       3
7        3       14       4
8        3       15       5
9        3       16       3


In [26]:
# 1- 3, 2- 2, 3-5
ratings1['user_id'].value_counts()

user_id
3    5
1    3
2    2
Name: count, dtype: int64

In [27]:
# get the users who have given more thatn 3 times ratings ==>  3 - 5
x1 = ratings1['user_id'].value_counts() > 3
x1

user_id
3     True
1    False
2    False
Name: count, dtype: bool

In [28]:
type(x1)

pandas.core.series.Series

In [29]:
# boolean masking ==>conditional based selection
x1[x1]

user_id
3    True
Name: count, dtype: bool

In [30]:
x1[x1].index

Index([3], dtype='int64', name='user_id')

In [31]:
y1 = x1[x1].index

In [32]:
condition1 = ratings1['user_id'].isin(y1)
condition1

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
9     True
Name: user_id, dtype: bool

In [33]:
filtered1 = ratings1[condition1]
filtered1

user_id  book_id  rating
5        3       11       2
6        3       12       3
7        3       14       4
8        3       15       5
9        3       16       3

## Actual Program

In [34]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...  
119573        1
276706        1
276697        1
276679        1
276676        1
Name: count, Length: 105283, dtype: int64

In [35]:
# Filter the records who has given more than 200 times of ratings
x = ratings['user_id'].value_counts() > 200

In [36]:
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...  
119573    False
276706    False
276697    False
276679    False
276676    False
Name: count, Length: 105283, dtype: bool

In [37]:
x[x].shape

(899,)

In [38]:
y = x[x].index

In [39]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       116122,  44296,  28634,  59727,  73681, 274808, 188951,   9856, 155916,
       268622],
      dtype='int64', name='user_id', length=899)

In [40]:
condition = ratings['user_id'].isin(y)
condition

0          False
1          False
2          False
3          False
4          False
           ...  
1149775    False
1149776    False
1149777    False
1149778    False
1149779    False
Name: user_id, Length: 1149780, dtype: bool

In [41]:
ratings = ratings[condition]

In [42]:
ratings.shape

(526356, 3)

In [43]:
ratings.head()

user_id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

# Merge Books + ratings
- ratings ==> we will have only ISBN
- books ==> entire meta data information about book
- what is the common column between books and ratings ==> `ISBN`


In [44]:
books.shape, ratings.shape

((271360, 6), (526356, 3))

In [45]:
ratings_with_books = ratings.merge(books,on='ISBN')

In [46]:
ratings_with_books.shape

(487671, 8)

In [47]:
ratings_with_books.head()

user_id        ISBN  rating  \
0   277427  002542730X      10   
1   277427  0026217457       0   
2   277427  003008685X       8   
3   277427  0030615321       0   
4   277427  0060002050       0   

                                               title                 author  \
0  Politically Correct Bedtime Stories: Modern Ta...      James Finn Garner   
1                 Vegetarian Times Complete Cookbook             Lucy  Moll   
2                                           Pioneers  James Fenimore Cooper   
3   Ask for May, Settle for June (A Doonesbury book)          G. B. Trudeau   
4                  On a Wicked Dawn (Cynster Novels)      Stephanie Laurens   

   year                  publisher  \
0  1994  John Wiley &amp; Sons Inc   
1  1995      John Wiley &amp; Sons   
2  1974           Thomson Learning   
3  1982        Henry Holt &amp; Co   
4  2002                 Avon Books   

                                           image_url  
0  http://images.amazon.com/images/P/002542730X.0...  
1  http://images.amazon.com/images/P/0026217457.0...  
2  http://images.amazon.com/images/P/003008685X.0...  
3  http://images.amazon.com/images/P/0030615321.0...  
4  http://images.amazon.com/images/P/0060002050.0...

In [48]:
type(ratings_with_books.groupby('title')['rating'])

pandas.core.groupby.generic.SeriesGroupBy

In [49]:
number_rating = ratings_with_books.groupby('title')['rating'].count().reset_index()
number_rating

title  rating
0        A Light in the Storm: The Civil War Diary of ...       2
1                                   Always Have Popsicles       1
2                    Apple Magic (The Collector's series)       1
3        Beyond IBM: Leadership Marketing and Finance ...       1
4        Clifford Visita El Hospital (Clifford El Gran...       1
...                                                   ...     ...
160264  Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...       3
160265                                      Ã?Â?lpiraten.       1
160266                     Ã?Â?rger mit Produkt X. Roman.       1
160267                              Ã?Â?stlich der Berge.       1
160268                                  Ã?Â?thique en toc       1

[160269 rows x 2 columns]

In [50]:
# rename the column
number_rating.rename(columns = {'rating':'num_of_rating'}, inplace= True)

In [51]:
number_rating.head()

title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [52]:
final_rating = ratings_with_books.merge(number_rating,on='title')
final_rating

user_id        ISBN  rating  \
0        277427  002542730X      10   
1        277427  0026217457       0   
2        277427  003008685X       8   
3        277427  0030615321       0   
4        277427  0060002050       0   
...         ...         ...     ...   
487666   275970  1931868123       0   
487667   275970  3411086211      10   
487668   275970  3829021860       0   
487669   275970  4770019572       0   
487670   275970  9626340762       8   

                                                    title  \
0       Politically Correct Bedtime Stories: Modern Ta...   
1                      Vegetarian Times Complete Cookbook   
2                                                Pioneers   
3        Ask for May, Settle for June (A Doonesbury book)   
4                       On a Wicked Dawn (Cynster Novels)   
...                                                   ...   
487666  There's a Porcupine in My Outhouse: Misadventu...   
487667                                         Die Biene.   
487668                                     The Penis Book   
487669                                            Musashi   
487670  Northanger Abbey (Classic Literature with Clas...   

                               author  year  \
0                   James Finn Garner  1994   
1                          Lucy  Moll  1995   
2               James Fenimore Cooper  1974   
3                       G. B. Trudeau  1982   
4                   Stephanie Laurens  2002   
...                               ...   ...   
487666                   Mike Tougias  2002   
487667  Sybil Gr�¤fin Sch�¶nfeldt  1993   
487668                   Joseph Cohen  1999   
487669                 Eiji Yoshikawa  1995   
487670                    Jane Austen  1996   

                                   publisher  \
0                  John Wiley &amp; Sons Inc   
1                      John Wiley &amp; Sons   
2                           Thomson Learning   
3                        Henry Holt &amp; Co   
4                                 Avon Books   
...                                      ...   
487666                    Capital Books (VA)   
487667  Bibliographisches Institut, Mannheim   
487668                              Konemann   
487669          Kodansha International (JPN)   
487670                 Naxos Audiobooks Ltd.   

                                                image_url  num_of_rating  
0       http://images.amazon.com/images/P/002542730X.0...             82  
1       http://images.amazon.com/images/P/0026217457.0...              7  
2       http://images.amazon.com/images/P/003008685X.0...              1  
3       http://images.amazon.com/images/P/0030615321.0...              1  
4       http://images.amazon.com/images/P/0060002050.0...             13  
...                                                   ...            ...  
487666  http://images.amazon.com/images/P/1931868123.0...              1  
487667  http://images.amazon.com/images/P/3411086211.0...              1  
487668  http://images.amazon.com/images/P/3829021860.0...              1  
487669  http://images.amazon.com/images/P/4770019572.0...              1  
487670  http://images.amazon.com/images/P/9626340762.0...              2  

[487671 rows x 9 columns]

In [53]:
# final_rating.T

In [54]:
final_rating

user_id        ISBN  rating  \
0        277427  002542730X      10   
1        277427  0026217457       0   
2        277427  003008685X       8   
3        277427  0030615321       0   
4        277427  0060002050       0   
...         ...         ...     ...   
487666   275970  1931868123       0   
487667   275970  3411086211      10   
487668   275970  3829021860       0   
487669   275970  4770019572       0   
487670   275970  9626340762       8   

                                                    title  \
0       Politically Correct Bedtime Stories: Modern Ta...   
1                      Vegetarian Times Complete Cookbook   
2                                                Pioneers   
3        Ask for May, Settle for June (A Doonesbury book)   
4                       On a Wicked Dawn (Cynster Novels)   
...                                                   ...   
487666  There's a Porcupine in My Outhouse: Misadventu...   
487667                                         Die Biene.   
487668                                     The Penis Book   
487669                                            Musashi   
487670  Northanger Abbey (Classic Literature with Clas...   

                               author  year  \
0                   James Finn Garner  1994   
1                          Lucy  Moll  1995   
2               James Fenimore Cooper  1974   
3                       G. B. Trudeau  1982   
4                   Stephanie Laurens  2002   
...                               ...   ...   
487666                   Mike Tougias  2002   
487667  Sybil Gr�¤fin Sch�¶nfeldt  1993   
487668                   Joseph Cohen  1999   
487669                 Eiji Yoshikawa  1995   
487670                    Jane Austen  1996   

                                   publisher  \
0                  John Wiley &amp; Sons Inc   
1                      John Wiley &amp; Sons   
2                           Thomson Learning   
3                        Henry Holt &amp; Co   
4                                 Avon Books   
...                                      ...   
487666                    Capital Books (VA)   
487667  Bibliographisches Institut, Mannheim   
487668                              Konemann   
487669          Kodansha International (JPN)   
487670                 Naxos Audiobooks Ltd.   

                                                image_url  num_of_rating  
0       http://images.amazon.com/images/P/002542730X.0...             82  
1       http://images.amazon.com/images/P/0026217457.0...              7  
2       http://images.amazon.com/images/P/003008685X.0...              1  
3       http://images.amazon.com/images/P/0030615321.0...              1  
4       http://images.amazon.com/images/P/0060002050.0...             13  
...                                                   ...            ...  
487666  http://images.amazon.com/images/P/1931868123.0...              1  
487667  http://images.amazon.com/images/P/3411086211.0...              1  
487668  http://images.amazon.com/images/P/3829021860.0...              1  
487669  http://images.amazon.com/images/P/4770019572.0...              1  
487670  http://images.amazon.com/images/P/9626340762.0...              2  

[487671 rows x 9 columns]

In [55]:
condition1 = final_rating['num_of_rating'] >=50
condition1

0          True
1         False
2         False
3         False
4         False
          ...  
487666    False
487667    False
487668    False
487669    False
487670    False
Name: num_of_rating, Length: 487671, dtype: bool

In [56]:
final_rating = final_rating[condition1]
final_rating

user_id        ISBN  rating  \
0        277427  002542730X      10   
13       277427  0060930535       0   
15       277427  0060934417       0   
18       277427  0061009059       9   
24       277427  006440188X       0   
...         ...         ...     ...   
487505   275970  1400031354       0   
487506   275970  1400031362       0   
487579   275970  1573229725       0   
487618   275970  1586210661       9   
487619   275970  1586212230       0   

                                                    title  \
0       Politically Correct Bedtime Stories: Modern Ta...   
13                          The Poisonwood Bible: A Novel   
15                                     Bel Canto: A Novel   
18      One for the Money (Stephanie Plum Novels (Pape...   
24                                      The Secret Garden   
...                                                   ...   
487505  Tears of the Giraffe (No.1 Ladies Detective Ag...   
487506  Morality for Beautiful Girls (No.1 Ladies Dete...   
487579                                        Fingersmith   
487618                             Me Talk Pretty One Day   
487619                                              Naked   

                         author  year                  publisher  \
0             James Finn Garner  1994  John Wiley &amp; Sons Inc   
13           Barbara Kingsolver  1999                  Perennial   
15                 Ann Patchett  2002                  Perennial   
18              Janet Evanovich  1995                HarperTorch   
24      Frances Hodgson Burnett  1998               HarperTrophy   
...                         ...   ...                        ...   
487505   Alexander McCall Smith  2002                     Anchor   
487506   Alexander McCall Smith  2002                     Anchor   
487579             Sarah Waters  2002            Riverhead Books   
487618            David Sedaris  2001    Time Warner Audio Major   
487619            David Sedaris  2001    Time Warner Audio Major   

                                                image_url  num_of_rating  
0       http://images.amazon.com/images/P/002542730X.0...             82  
13      http://images.amazon.com/images/P/0060930535.0...            133  
15      http://images.amazon.com/images/P/0060934417.0...            108  
18      http://images.amazon.com/images/P/0061009059.0...            108  
24      http://images.amazon.com/images/P/006440188X.0...             79  
...                                                   ...            ...  
487505  http://images.amazon.com/images/P/1400031354.0...             84  
487506  http://images.amazon.com/images/P/1400031362.0...             60  
487579  http://images.amazon.com/images/P/1573229725.0...             59  
487618  http://images.amazon.com/images/P/1586210661.0...            146  
487619  http://images.amazon.com/images/P/1586212230.0...             53  

[61853 rows x 9 columns]

In [57]:
final_rating.shape

(61853, 9)

In [58]:
final_rating.columns

Index(['user_id', 'ISBN', 'rating', 'title', 'author', 'year', 'publisher',
       'image_url', 'num_of_rating'],
      dtype='object')

In [59]:
# remove the duplicate from the final_rating
# user_id, title ==> are having duplicates
final_rating.drop_duplicates(['user_id','title'],inplace=True)

C:\Users\Gopi\AppData\Local\Temp\ipykernel_31008\1697131279.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['user_id','title'],inplace=True)


In [60]:
final_rating.shape

(59850, 9)

In [61]:
487671 - 483423

4248

In [62]:
# check for the null values
final_rating.isnull().sum()

user_id          0
ISBN             0
rating           0
title            0
author           0
year             0
publisher        0
image_url        0
num_of_rating    0
dtype: int64

# Pivot table creation

- Convert long format → wide format.
- Structure:
    -  Rows → Book-Title
    -  Columns → User-ID
    -  Values → Book-Rating
- Each book becomes a vector in high-dimensional space

In [63]:
book_pivot = final_rating.pivot_table(columns='user_id', index='title', values='rating')
book_pivot

user_id                                             254     2276    2766    \
title                                                                        
1984                                                   9.0     NaN     NaN   
1st to Die: A Novel                                    NaN     NaN     NaN   
2nd Chance                                             NaN    10.0     NaN   
4 Blondes                                              NaN     NaN     NaN   
84 Charing Cross Road                                  NaN     NaN     NaN   
...                                                    ...     ...     ...   
Year of Wonders                                        NaN     NaN     NaN   
You Belong To Me                                       NaN     NaN     NaN   
Zen and the Art of Motorcycle Maintenance: An I...     NaN     NaN     NaN   
Zoya                                                   NaN     NaN     NaN   
\O\" Is for Outlaw"                                    NaN     NaN     NaN   

user_id                                             2977    3363    3757    \
title                                                                        
1984                                                   NaN     NaN     NaN   
1st to Die: A Novel                                    NaN     NaN     NaN   
2nd Chance                                             NaN     NaN     NaN   
4 Blondes                                              NaN     NaN     NaN   
84 Charing Cross Road                                  NaN     NaN     NaN   
...                                                    ...     ...     ...   
Year of Wonders                                        7.0     NaN     NaN   
You Belong To Me                                       NaN     NaN     NaN   
Zen and the Art of Motorcycle Maintenance: An I...     NaN     0.0     NaN   
Zoya                                                   NaN     NaN     NaN   
\O\" Is for Outlaw"                                    NaN     NaN     NaN   

user_id                                             4017    4385    6242    \
title                                                                        
1984                                                   NaN     NaN     NaN   
1st to Die: A Novel                                    NaN     NaN     NaN   
2nd Chance                                             NaN     NaN     NaN   
4 Blondes                                              NaN     NaN     NaN   
84 Charing Cross Road                                  NaN     NaN     NaN   
...                                                    ...     ...     ...   
Year of Wonders                                        NaN     NaN     7.0   
You Belong To Me                                       NaN     NaN     NaN   
Zen and the Art of Motorcycle Maintenance: An I...     NaN     NaN     NaN   
Zoya                                                   NaN     NaN     NaN   
\O\" Is for Outlaw"                                    NaN     NaN     NaN   

user_id                                             6251    ...  274004  \
title                                                       ...           
1984                                                   NaN  ...     NaN   
1st to Die: A Novel                                    NaN  ...     NaN   
2nd Chance                                             NaN  ...     NaN   
4 Blondes                                              0.0  ...     NaN   
84 Charing Cross Road                                  NaN  ...     NaN   
...                                                    ...  ...     ...   
Year of Wonders                                        NaN  ...     NaN   
You Belong To Me                                       NaN  ...     NaN   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     NaN   
Zoya                                                   NaN  ...     NaN   
\O\" Is for Outlaw"                                    

**Note**
- Replace `NAN` with `0`
- `NAN` ==> NotANumber

In [64]:
book_pivot.fillna(0,inplace=True)

In [65]:
book_pivot

user_id                                             254     2276    2766    \
title                                                                        
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
84 Charing Cross Road                                  0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user_id                                             2977    3363    3757    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
84 Charing Cross Road                                  0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        7.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user_id                                             4017    4385    6242    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
84 Charing Cross Road                                  0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     7.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user_id                                             6251    ...  274004  \
title                                                       ...           
1984                                                   0.0  ...     0.0   
1st to Die: A Novel                                    0.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
84 Charing Cross Road                                  0.0  ...     0.0   
...                                                    ...  ...     ...   
Year of Wonders                                        0.0  ...     0.0   
You Belong To Me                                       0.0  ...     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0   
Zoya                                                   0.0  ...     0.0   
\O\" Is for Outlaw"                                    

**Note**
- our data contains most of `0`s ==> sparse data
- it will consumes lot of memory
- A CSR matrix (Compressed Sparse Row matrix) is a memory-efficient way to store sparse data
- It is heavily used in machine learning, recommender systems, NLP, and GenAI because real datasets (ratings, tokens, embeddings) are often sparse
- in scipy `csr_matrix` is present
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html

In [66]:
from scipy.sparse import csr_matrix

In [68]:
# help(csr_matrix)

In [69]:
import numpy as np

In [70]:
book_sparse = csr_matrix(book_pivot)

In [71]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

```
data ==> CSR format data array of the matrix

indices ==> CSR format index array of the matrix

indptr ==> CSR format index pointer array of the matrix
```

In [72]:
book_sparse.data

array([ 9.,  8.,  9., ..., 10.,  9.,  8.], shape=(14961,))

In [73]:
book_sparse.indices

array([  0,  16,  37, ..., 745, 830, 880], shape=(14961,), dtype=int32)

In [74]:
book_sparse.indptr

array([    0,    27,    70,   104,   117,   142,   168,   183,   208,
         214,   225,   237,   243,   253,   264,   280,   314,   328,
         341,   351,   374,   428,   439,   470,   479,   491,   545,
         556,   585,   597,   620,   653,   668,   696,   702,   725,
         733,   745,   762,   781,   789,   813,   825,   853,   875,
         883,   907,   929,   937,   957,   987,   998,  1052,  1071,
        1083,  1109,  1135,  1158,  1188,  1202,  1229,  1248,  1269,
        1282,  1318,  1341,  1357,  1393,  1414,  1419,  1433,  1445,
        1481,  1502,  1519,  1534,  1557,  1586,  1601,  1610,  1626,
        1637,  1664,  1684,  1703,  1724,  1737,  1749,  1770,  1789,
        1803,  1823,  1837,  1855,  1868,  1882,  1966,  1988,  2003,
        2028,  2032,  2046,  2058,  2081,  2107,  2121,  2132,  2155,
        2167,  2189,  2206,  2229,  2252,  2278,  2287,  2306,  2325,
        2334,  2353,  2363,  2376,  2400,  2419,  2425,  2433,  2475,
        2499,  2524,

In [75]:
from sklearn.neighbors import NearestNeighbors

In [76]:
model = NearestNeighbors(algorithm='brute')

In [77]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

# Test the model

In [78]:
book_pivot.iloc[237,:]

user_id
254       9.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ... 
275970    9.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: Harry Potter and the Chamber of Secrets (Book 2), Length: 888, dtype: float64

In [79]:
book_pivot.iloc[237,:].shape

(888,)

In [80]:
book_pivot.iloc[237,:].values

array([ 9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,
       10.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        9.,  0.,  0.,  0., 10.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  7.,  9.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [ ]:
book_pivot.iloc[237,:].values.reshape()

In [81]:
a = np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [82]:
a.ndim

1

In [83]:
a.shape

(4,)

In [84]:
a.reshape(1,-1)

array([[10, 20, 30, 40]])

In [85]:
distance,suggestion = model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [86]:
distance

array([[ 0.        , 67.75691847, 68.05145112, 72.277244  , 75.81556568,
        76.30203143]])

In [87]:
suggestion

array([[237, 238, 240, 241, 184, 536]])

In [88]:
# to get the names of the books
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='object', name='title')


In [89]:
# to get the book names
book_pivot.index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=742)

In [90]:
book_names = book_pivot.index

In [91]:
book_names[3]

'4 Blondes'

In [92]:
book_names[0]

'1984'

In [93]:
# [237, 238, 240, 241, 184, 536]
book_names[237]

'Harry Potter and the Chamber of Secrets (Book 2)'

In [94]:
book_names[238]

'Harry Potter and the Goblet of Fire (Book 4)'

In [96]:
final_rating.columns

Index(['user_id', 'ISBN', 'rating', 'title', 'author', 'year', 'publisher',
       'image_url', 'num_of_rating'],
      dtype='object')

In [97]:
np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')

(array([237]),)

In [98]:
type(np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)'))

tuple

In [99]:
np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')[0]

array([237])

In [100]:
type(np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')[0])

numpy.ndarray

In [101]:
np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')[0].ndim

1

In [102]:
np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')[0][0]

np.int64(237)

In [103]:
ids = np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')[0][0]

In [104]:
ids

np.int64(237)

In [105]:
final_rating.iloc[ids]

user_id                                                     278418
ISBN                                                    0451128370
rating                                                           0
title                                                    Christine
author                                                Stephen King
year                                                          1983
publisher                                      Penguin Putnam~mass
image_url        http://images.amazon.com/images/P/0451128370.0...
num_of_rating                                                   67
Name: 3065, dtype: object

In [106]:
final_rating.iloc[ids]['image_url']

'http://images.amazon.com/images/P/0451128370.01.LZZZZZZZ.jpg'

In [108]:
final_rating.iloc[321]['image_url']

'http://images.amazon.com/images/P/0439139597.01.LZZZZZZZ.jpg'

In [109]:
suggestion

array([[237, 238, 240, 241, 184, 536]])

In [110]:
# to get the names of the books in a list
book_name = []
for book_id in suggestion:
    book_name.append(book_pivot.index[book_id])

In [111]:
book_name

[Index(['Harry Potter and the Chamber of Secrets (Book 2)',
        'Harry Potter and the Goblet of Fire (Book 4)',
        'Harry Potter and the Prisoner of Azkaban (Book 3)',
        'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
        'The Cradle Will Fall'],
       dtype='object', name='title')]

In [115]:
final_rating.columns

Index(['user_id', 'ISBN', 'rating', 'title', 'author', 'year', 'publisher',
       'image_url', 'num_of_rating'],
      dtype='object')

In [112]:
# extract the ids of the books from final_rating dataframe
ids_index = []
for name in book_name[0]: 
    ids = np.where(final_rating['title'] == name)[0][0]
    ids_index.append(ids)

In [113]:
ids_index

[np.int64(44),
 np.int64(321),
 np.int64(45),
 np.int64(46),
 np.int64(786),
 np.int64(2297)]

In [116]:
# extract image urls
for idx in ids_index:
    url = final_rating.iloc[idx]['image_url']
    print(url)

http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0439139597.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0439136369.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/043936213X.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446604232.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0440115450.01.LZZZZZZZ.jpg


In [117]:
book_names

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=742)

In [118]:
model

NearestNeighbors(algorithm='brute')

In [120]:
final_rating

user_id        ISBN  rating  \
0        277427  002542730X      10   
13       277427  0060930535       0   
15       277427  0060934417       0   
18       277427  0061009059       9   
24       277427  006440188X       0   
...         ...         ...     ...   
487505   275970  1400031354       0   
487506   275970  1400031362       0   
487579   275970  1573229725       0   
487618   275970  1586210661       9   
487619   275970  1586212230       0   

                                                    title  \
0       Politically Correct Bedtime Stories: Modern Ta...   
13                          The Poisonwood Bible: A Novel   
15                                     Bel Canto: A Novel   
18      One for the Money (Stephanie Plum Novels (Pape...   
24                                      The Secret Garden   
...                                                   ...   
487505  Tears of the Giraffe (No.1 Ladies Detective Ag...   
487506  Morality for Beautiful Girls (No.1 Ladies Dete...   
487579                                        Fingersmith   
487618                             Me Talk Pretty One Day   
487619                                              Naked   

                         author  year                  publisher  \
0             James Finn Garner  1994  John Wiley &amp; Sons Inc   
13           Barbara Kingsolver  1999                  Perennial   
15                 Ann Patchett  2002                  Perennial   
18              Janet Evanovich  1995                HarperTorch   
24      Frances Hodgson Burnett  1998               HarperTrophy   
...                         ...   ...                        ...   
487505   Alexander McCall Smith  2002                     Anchor   
487506   Alexander McCall Smith  2002                     Anchor   
487579             Sarah Waters  2002            Riverhead Books   
487618            David Sedaris  2001    Time Warner Audio Major   
487619            David Sedaris  2001    Time Warner Audio Major   

                                                image_url  num_of_rating  
0       http://images.amazon.com/images/P/002542730X.0...             82  
13      http://images.amazon.com/images/P/0060930535.0...            133  
15      http://images.amazon.com/images/P/0060934417.0...            108  
18      http://images.amazon.com/images/P/0061009059.0...            108  
24      http://images.amazon.com/images/P/006440188X.0...             79  
...                                                   ...            ...  
487505  http://images.amazon.com/images/P/1400031354.0...             84  
487506  http://images.amazon.com/images/P/1400031362.0...             60  
487579  http://images.amazon.com/images/P/1573229725.0...             59  
487618  http://images.amazon.com/images/P/1586210661.0...            146  
487619  http://images.amazon.com/images/P/1586212230.0...             53  

[59850 rows x 9 columns]

In [121]:
book_pivot

user_id                                             254     2276    2766    \
title                                                                        
1984                                                   9.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0    10.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
84 Charing Cross Road                                  0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user_id                                             2977    3363    3757    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
84 Charing Cross Road                                  0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        7.0     0.0     0.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user_id                                             4017    4385    6242    \
title                                                                        
1984                                                   0.0     0.0     0.0   
1st to Die: A Novel                                    0.0     0.0     0.0   
2nd Chance                                             0.0     0.0     0.0   
4 Blondes                                              0.0     0.0     0.0   
84 Charing Cross Road                                  0.0     0.0     0.0   
...                                                    ...     ...     ...   
Year of Wonders                                        0.0     0.0     7.0   
You Belong To Me                                       0.0     0.0     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0     0.0     0.0   
Zoya                                                   0.0     0.0     0.0   
\O\" Is for Outlaw"                                    0.0     0.0     0.0   

user_id                                             6251    ...  274004  \
title                                                       ...           
1984                                                   0.0  ...     0.0   
1st to Die: A Novel                                    0.0  ...     0.0   
2nd Chance                                             0.0  ...     0.0   
4 Blondes                                              0.0  ...     0.0   
84 Charing Cross Road                                  0.0  ...     0.0   
...                                                    ...  ...     ...   
Year of Wonders                                        0.0  ...     0.0   
You Belong To Me                                       0.0  ...     0.0   
Zen and the Art of Motorcycle Maintenance: An I...     0.0  ...     0.0   
Zoya                                                   0.0  ...     0.0   
\O\" Is for Outlaw"                                    

In [122]:
import pickle
pickle.dump(model,open('model.pkl','wb'))
pickle.dump(book_names,open('book_names.pkl','wb'))
pickle.dump(final_rating,open('final_rating.pkl','wb'))
pickle.dump(book_pivot,open('book_pivot.pkl','wb'))
print("Models are saved successfully")

Models are saved successfully


# Testing the model using a function

In [123]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1), n_neighbors=6 )
    
    for i in range(len(suggestion)):
            books = book_pivot.index[suggestion[i]]
            for j in books:
                if j == book_name:
                    print(f"You searched '{book_name}'\n")
                    print("The suggestion books are: \n")
                else:
                    print(j)

In [124]:
recommend_book("2nd Chance")

You searched '2nd Chance'

The suggestion books are: 

The Next Accident
The Ghost
Exclusive
Last Man Standing
Unspeakable
